### ISSUE TITLE
Z czystej ciekawości

### ISSUE THREAD

**Issue by krzysztofantczak** [openpkw/openpkw-kalkulator-obwodowy-web#11]
Dlaczego grunt, a nie gulp?

**Comment by SebastianCelejewski** [comment]
Osoby, które były uprzejme i poświęciły czas na zaimplementowanie tego, użyły grunta. Gdyby robił to ktoś inny, być może wybrałby gulpa.

**Comment by SebastianCelejewski** [comment]
Zamykam, ponieważ nie jest to ,,issue''.
